apiVersion: v1
kind: Secret
metadata:
  name: db2-secret
  namespace: mydb2app
type: Opaque
stringData:
  DB2_USER: db2inst1
  DB2_PASSWORD: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mydb2app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # Ensure pod schedules only on AMD64 nodes
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: backend
        image: docker.io/abhianand2015/db2-sp-backend-git:latest 
        ports:
        - containerPort: 8000
        env:
        - name: DB2_HOST
          value: "db2-service"
        - name: DB2_PORT
          value: "50000"
        - name: DB2_NAME
          value: "TESTDB"
        - name: DB2_USER
          valueFrom:
            secretKeyRef:
              name: db2-secret
              key: DB2_USER
        - name: DB2_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db2-secret
              key: DB2_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mydb2app
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30008
  type: NodePort
